### ISSUE TITLE
Create transition function

### ISSUE THREAD

**Issue by goweiwen** [JYL123/CS3243-Project#1]
Given a current `State` and an action `[orientation, columnNum]`, return the resultant `State`.

**Comment by k-l-a** [comment]
Isn't this already in the base code as makeMove(int orient, int slot)?

**Comment by goweiwen** [comment]
Yes, but from what I tried, there doesn't seem to be a way to clone or rollback a `State` object. Since the `State` object provided is used by the game, we should not use its `makeMove`.

Is there an easier way that I'm missing out?

**Comment by k-l-a** [comment]
Ah, I understand what you're trying to do now. You're right, there's currently no implementation to get the next State while preserving the current State easily.
